### PR TITLE
add image used in tutorial

### PR DESCRIPTION
**Pull request by astraw**
This adds the image used in the tutorial.

### CODE REVIEW

**Comment by vadixidav** [comment]
Actually, it looks like we just need to point the path to go up two directories to point to the res folder. I don't want multiple copies of the image in the repo.

**Comment by astraw** [comment]
git will store only one copy (because they have the same hash) but yes the working copy checkout will have two separate files.

**Comment by astraw** [comment]
OK, well, I added an alternative approach in #30. As it is now, the tutorial will not run.

**Comment by vadixidav** [comment]
Other approach was accepted. Thank you. I will close this one.

**Pull request closed without merging**
