### PR TITLE
Fix akaze orientation (from upstream branch)

### PR DESCRIPTION
**Pull request by vadixidav**
This is the same branch as #64 but added to the upstream repository as the original branch was not modifiable by maintainers.

### CODE REVIEW

**Comment by vadixidav** [comment]
@stephanemagnenat I have incorporated your changes along with my own. Could you please compare the Rust CV `akaze` against the OpenCV implementation again to see if the behavior is now the same.

**Comment by stephanemagnenat** [comment]
Further corrections in #66, with the debug dumps.

**Comment by stephanemagnenat** [comment]
Ok, now it works, thanks!

**Review by xd009642 — APPROVED** [review]
Checked and we're happy to merge. Thanks for all the hard work!

**Pull request merged**
