### PR TITLE
Add Github workflow to build all projects.

### LINKED ISSUE #26: Make Github workflow build all projects
As we discused in the Discord server the CI does not attempt to build all the projects today. A few build error can slip through because of this.

### PR DESCRIPTION
**Pull request by codec-abc**
Add Github workflow to build all projects. Fix #26 .

### CODE REVIEW

**Comment by vadixidav** [comment]
Can you also add a new badge for this build to the readme. You can just copy how the other entries in the readme work.

**Comment by vadixidav** [comment]
You need to give that badge a different name than bll and also add it to the badges further up in the readme.

**Comment by codec-abc** [comment]
Sorry for the mistake. Do you know why the last build didn't pass the CI?

Both seems to have failed with
```
Run actions-rs/cargo@v1
/usr/share/rust/.cargo/bin/cargo build --all --all-features
    Updating crates.io index
    Updating git repository `https://github.com/vadixidav/argmin.git`
   Compiling cv-core v0.15.0 (/home/runner/work/cv/cv/cv-core)
   Compiling imgshow v0.1.0 (/home/runner/work/cv/cv/imgshow)
error: could not compile `cv-core`
Error: could not compile `cv-core`
Caused by:
  process didn't exit successfully: `rustc --crate-name cv_core --edition=2018 cv-core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=on --cfg 'feature="serde"' --cfg 'feature="serde-serialize"' -C metadata=8d106bec3fa8b80b -C extra-filename=-8d106bec3fa8b80b --out-dir /home/runner/work/cv/cv/target/debug/deps -C incremental=/home/runner/work/cv/cv/target/debug/incremental -L dependency=/home/runner/work/cv/cv/target/debug/deps --extern derive_more=/home/runner/work/cv/cv/target/debug/deps/libderive_more-472f825531d45ce2.so --extern nalgebra=/home/runner/work/cv/cv/target/debug/deps/libnalgebra-cabc0cd738df9376.rmeta --extern num_traits=/home/runner/work/cv/cv/target/debug/deps/libnum_traits-44698b5af3f012c6.rmeta --extern sample_consensus=/home/runner/work/cv/cv/target/debug/deps/libsample_consensus-a92e74415d18b8a4.rmeta --extern serde=/home/runner/work/cv/cv/target/debug/deps/libserde-081f3ef00437384e.rmeta -C target-cpu=native` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
Warning: error: build failed
Error: The process '/usr/share/rust/.cargo/bin/cargo' failed with exit code 101
```

Does this happen often with Github worflow?

**Comment by vadixidav** [comment]
@codec-abc I haven't seen this happen before, but it says there was an illegal instruction executed. This makes me think that it executed an instruction that isn't supported on the CI machine. I can't really comment beyond that. It could have also been a random bit flip in the program or in memory. Running it again should be fine.

**Pull request merged**
