### PR TITLE
Replace imgshow with egui

### PR DESCRIPTION
**Pull request by Muqito**
Hello

I saw this issue:

#36

I thought I could maybe help out tackle it by just replacing the image library
rust-cv

### CODE REVIEW

**Comment by vadixidav** [comment]
Excellent. There is a clippy lint that needs to be corrected, but aside from that this looks good to me. Thank you for taking the time to swap out iced for egui.

**Comment by Muqito** [comment]
@vadixidav 

Clippy doesn't fail on my part any longer. But I got this in the build:

```
Error: could not compile `cv-core`
Caused by:
  process didn't exit successfully: `/usr/share/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/clippy-driver rustc --crate-name cv_core --edition=2018 cv-core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata -C opt-level=3 -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=on --cfg 'feature="serde"' --cfg 'feature="serde-serialize"' -C metadata=db38c54f53ad3cb6 -C extra-filename=-db38c54f53ad3cb6 --out-dir /home/runner/work/cv/cv/target/debug/deps -L dependency=/home/runner/work/cv/cv/target/debug/deps --extern derive_more=/home/runner/work/cv/cv/target/debug/deps/libderive_more-8594d7ea08880aa8.so --extern nalgebra=/home/runner/work/cv/cv/target/debug/deps/libnalgebra-84d6f4aa8fee8d6f.rmeta --extern num_traits=/home/runner/work/cv/cv/target/debug/deps/libnum_traits-a159647ae5e0f7a3.rmeta --extern sample_consensus=/home/runner/work/cv/cv/target/debug/deps/libsample_consensus-b71bb157d2f7897b.rmeta --extern serde=/home/runner/work/cv/cv/target/debug/deps/libserde-e49022d472329fea.rmeta -C target-cpu=native` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
```

**Comment by vadixidav** [comment]
The GitHub CI has been fairly inconsistent for me. I will clone your changes and test it locally, then merge. I really wish I knew why these issues keep occuring in CI, such as the SIGKILL in the build.

**Comment by Muqito** [comment]
> The GitHub CI has been fairly inconsistent for me. I will clone your changes and test it locally, then merge. I really wish I knew why these issues keep occuring in CI, such as the SIGKILL in the build.

If you want I can take a look at the CI/CD build as well? Set up on my branch

**Comment by vadixidav** [comment]
Since the OS image viewer is now used instead of a Rust-based viewer, I will go ahead and close this. Thank you nonetheless.

**Pull request closed without merging**
