### PR TITLE
Updated dependencies and updated code: image and imageprocs

### PR DESCRIPTION
**Pull request by stephanemagnenat**
This updates image to 0.24 and imageprocs to 0.23, to keep up with the other packages in the community.

### CODE REVIEW

**Review by xd009642 — APPROVED** [review]
LGTM, the clippy and fmt changes are unrelated to yours so I'll just merge now and fix them in a bit!

**Comment by xd009642** [comment]
Oh actually the cargo fmt failure is from this PR, could you fix that and then we're good to go!

**Comment by stephanemagnenat** [comment]
I have rebased on latest main, run fmt and made clippy happy!

**Comment by xd009642** [comment]
Awesome thanks :+1:

**Pull request merged**
