### PR TITLE
Replace imgshow with egui

### PR DESCRIPTION
**Pull request by Muqito**
Hello

I saw this issue:

https://github.com/rust-cv/cv/issues/36

I thought I could maybe help out tackle it by just replacing the image library

rust-cv

### CODE REVIEW

**Comment by vadixidav** [comment]
I think there was a misunderstanding. egui is a GUI crate: https://crates.io/crates/egui. The ticket was to switch to that from iced.

**Comment by Muqito** [comment]
> I think there was a misunderstanding. egui is a GUI crate: https://crates.io/crates/egui. The ticket was to switch to that from iced.

But Iced was removed in the PR and at the same time using egui for the image show with the same API.

**Comment by vadixidav** [comment]
Oh, I saw the local crate called egui and I assumed something different. If you want to add the branch back I can reopen this. However, we cannot publish a crate named egui, as that would cause a name conflict. For now you can just add that code to imgshow itself.

**Comment by vadixidav** [comment]
I would also like to see if we can avoid that -> !. Perhaps we can use winit instead of glutin? ennona is using winit as well.

**Comment by Muqito** [comment]
Oki, I'll modify it

**Comment by Muqito** [comment]
@vadixidav Do I need to create a new PR?

https://github.com/Muqito/cv/commit/4192842186f3bc8a721e029ddc0ef6b4bfb965f8

**Comment by vadixidav** [comment]
It isn't letting me reopen it even through the branch exists again. You can create a new PR. Sorry for the confusion.

**Pull request closed without merging**
